name: RSS Social Poster

on:
  schedule:
    - cron: '*/22 * * * *' # Every 30 minutes
  workflow_dispatch:

jobs:
  post-to-social:
    runs-on: ubuntu-latest
    environment: socials

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Chrome for Puppeteer
        run: |
          npx puppeteer browsers install chrome

      - name: Install dependencies
        run: npm install

      - name: Create .env file from secrets
        run: |
          echo "RSS_URLS=${{ secrets.RSS_URLS }}" >> $GITHUB_ENV
          echo "FACEBOOK_PAGE_ID=${{ secrets.FACEBOOK_PAGE_ID }}" >> $GITHUB_ENV
          echo "USER_ACCESS_TOKEN=${{ secrets.USER_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "INSTAGRAM_USER_ID=${{ secrets.INSTAGRAM_USER_ID }}" >> $GITHUB_ENV
          echo "PINTEREST_EMAIL=${{ secrets.PINTEREST_EMAIL }}" >> $GITHUB_ENV
          echo "PINTEREST_PASSWORD=${{ secrets.PINTEREST_PASSWORD }}" >> $GITHUB_ENV

      - name: Run social poster script
        run: node index.js

      - name: Set up Git credentials
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}


      - name: Commit updated posted.json
        run: |
          git config --global user.email "killervapors02@gmail.com"
          git config --global user.name "GitHub Actions Bot"
          git add posted.json
          git commit -m "Update posted.json" || echo "No changes to commit"
          git push
